---

mega:

  expression:
    returns:

  type:
    uuid:

  boolean:
    type:
      =: =mega.type
      uuid: "mega.boolean"

    true: {}
    false: {}

  string:
    type:
      =: =mega.type
      uuid: "mega.string"

    literal: {}